export default {
    TEXT_ELEMENT: 'TEXT_ELEMENT',
    REACTIVE_ELEMENT: Symbol.for('REACTIVE_ELEMENT'),
    REACTIVE_FIBRE: Symbol.for('REACTIVE_FIBRE'),
    EFFECT_UPDATE: 'UPDATE',
    EFFECT_REPLACE: 'REPLACE',
    EFFECT_DELETE: 'DELETE'
}